environment:
  VisualStudioVersion: 11.0

configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

# http://help.appveyor.com/discussions/questions/311-x86-version-of-xunit
# xxxdisablexxx

test_script:
  - cd
  - cd C:\Tools\xUnit\*.*
  - copy C:\projects\cefsharp\CefSharp.Test\bin\x86\%configuration%\*.*
  - xunit.console.clr4.x86 CefSharp.Test.dll /appveyor
