environment:
  VisualStudioVersion: 11.0

shallow_clone: true

#configuration:
#  - Debug
#  - Release

#before_build:
#  - cmd: nuget restore

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1

test_script:
  - cd C:\projects\cefsharp\CefSharp.Test\bin\x86\%configuration%\
  - cd
  - REM copy C:\Tools\xUnit\*.*
  - REM xunit.console.clr4.x86 CefSharp.Test.dll /appveyor

artifacts:
  - path: NuGet\*.nupkg
