environment:
  VisualStudioVersion: 11.0

configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

test_script:
  - cd C:\projects\cefsharp\CefSharp.Test\bin\x86\%configuration%\
  - cd
  - copy C:\Tools\xUnit\*.*
  - xunit.console.clr4.x86 CefSharp.Test.dll /appveyor
